# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from time import sleep

class Test_Dldld():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_dldld(self):
    self.driver.get("https://tobeto.com/")
    self.driver.set_window_size(1552, 832)
    self.driver.switch_to.frame(8)
    sleep(5)
    self.driver.find_element(By.XPATH,"//div[@class='exw-open-launcher__container']").click()
    sleep(2)
    self.driver.switch_to.default_content()
    sleep(3)
    self.driver.switch_to.frame(7)
    self.driver.find_element(By.CLASS_NAME, "//div[@class='exw-header-buttons']/child::node()[1]").click()
    sleep(3)
    self.driver.close()
  
