URL = "https://tobeto.com/kayit-ol"
NAME = "firstName"
SURNAME = "lastName"
EMAIL = "email"
PASSWORD = "password"
PASSWORD_AGAIN = "passwordAgain"
REGISTER_BUTTON = "//*[@id='__next']/div/main/section/div/div/div[1]/div/div/button"
ACIK_RIZA_METNI = "contact"
UYELIK_SOZLESME = "membershipContrat"
EMAIL_ONAY = "emailConfirmation"
PHONE_ONAY = "phoneConfirmation"
PHONE_NUMBER = "phoneNumber"
RECAPTCHA = "//*[@id='recaptcha-anchor']/div[1]"
CONTINUE_BUTTON ="/html/body/div[5]/div/div/div/div/div/div[3]/button[2]" 
