ABOUT_US = '//*[@id="__next"]/div/section[2]/div/div[1]/div[1]/ul/li[1]/a'
FOR_INDIVUDUALS = '//*[@id="__next"]/div/section[2]/div/div[1]/div[1]/ul/li[2]/a'
FOR_INSTITUTIONS = '//*[@id="__next"]/div/section[2]/div/div[1]/div[1]/ul/li[3]/a'
CORPORATE_IDENTITY = '//*[@id="__next"]/div/section[2]/div/div[1]/div[1]/ul/li[4]/a'
FAQ = '//*[@id="__next"]/div/section[2]/div/div[1]/div[1]/ul/li[5]/a'
COMMUNICATION = '//*[@id="__next"]/div/section[2]/div/div[1]/div[1]/ul/li[6]/a'

MEMBERSHIP = '//*[@id="__next"]/div/section[2]/div/div[1]/div[2]/ul/li[1]/a'
KVKK = '//*[@id="__next"]/div/section[2]/div/div[1]/div[2]/ul/li[2]/a'
RELATED_PERSON = '//*[@id="__next"]/div/section[2]/div/div[1]/div[2]/ul/li[3]/a'
COOKIE_POLICY = '//*[@id="__next"]/div/section[2]/div/div[1]/div[2]/ul/li[4]/a'
WITHDRAWAL_FORM = '//*[@id="__next"]/div/section[2]/div/div[1]/div[2]/ul/li[5]/a'

FRONTEND = '//*[@id="__next"]/div/section[2]/div/div[1]/div[3]/ul/li[1]/a'
FULL_STACK = '//*[@id="__next"]/div/section[2]/div/div[1]/div[3]/ul/li[2]/a'
WEB_MOBILE = '//*[@id="__next"]/div/section[2]/div/div[1]/div[3]/ul/li[3]/a'
DATA_SCIENCE = '//*[@id="__next"]/div/section[2]/div/div[1]/div[3]/ul/li[4]/a'
CYBER_SECURITY = '//*[@id="__next"]/div/section[2]/div/div[1]/div[3]/ul/li[5]/a'
UX_UI = '//*[@id="__next"]/div/section[2]/div/div[1]/div[3]/ul/li[6]/a'