NAME_TAG = "email"
PSW_TAG = "password"
GIRIS_YAP_XPATH = "//*[@id='__next']/div/main/section/div/div/div[1]/div/form/button"
LESSONS = "lessons-tab"
DFG = "//*[@id='lessons-tab-pane']/div/div/div[2]"
SEARCH = "search"
EGITIM = "//*[@id='all-lessons-tab-pane']/div/p"
KURUM = "//*[@id='__next']/div/main/div[2]/div[1]/div/div[2]/div/div[1]/div[1]/div[2]"
ISTKOD ="//div[@class='select__multi-value__label' and text()='İstanbul Kodluyor']"
ISTKOD1 ="//*[@id='__next']/div/main/div[2]/div[1]/div/div[2]/div/div[1]/div[1]/div[1]/div[1]"
