LESSONS = "lessons-tab"
NAME_TAG = "email"
PSW_TAG = "password"
GIRIS_YAP_XPATH = "//*[@id='__next']/div/main/section/div/div/div[1]/div/form/button"
DFG = "//*[@id='lessons-tab-pane']/div/div/div[2]"
SENKRON = "//*[@id='all-lessons-tab-pane']/div/div[14]/div/div[2]/a"
IKON_LIKE = "like-button"
PERSON = "like-text"
ABOUT = "//*[@id='rc-tabs-0-tab-about']/div/span"
CONTENT = "//*[@id='rc-tabs-0-tab-content']/div/span"
RECORD = " //*[@class='ant-btn ant-btn-default btn']/span[text()='KAYDI AÇ']"
WORK = "//div[@class='ant-collapse-header' and @aria-expanded='true' and @role='button']"
WORK_DETAIL = "//div[@class='ant-collapse-content-box']/div[@class='homework-line clearfix'][1]//div[@class='homework-row-button']/button[@class='ant-btn ant-btn-default btn white']/span[text()='DETAY']"
